#easy_admin:
#    entities:
#        # List the entity class name you want to manage
#        - App\Entity\Product
#        - App\Entity\Category
#        - App\Entity\User
easy_admin:
   site_name: 'CRAI <em style="font-size: 80%;">Administration.</em>'
   design:
           brand_color: '#1ABC9C'
           menu:
               - label: 'Noticias'
                 children:
                   - { label: 'Noticias', icon: 'list', entity: 'Noticias' }
                   - { label: 'Comentarios', icon: 'list', entity: 'Comentarios' }
                   - { label: 'Respuestas a Comentarios', icon: 'list', entity: 'RespuestaComentario' }
               - label: 'Recursos'
                 children:
                   - { label: 'Categorias', icon: 'list', entity: 'CategoriasRecursosInformacion' }
                   - { label: 'Recursos de la Informacion', icon: 'list', entity: 'RecursosInformacion' }



   formats:
       date:     'd/m/Y'
       time:     'H:i'
       datetime: 'd/m/Y H:i:s'
   entities:
           Noticias:
               class: App\Entity\Noticias
               label: 'Noticias'
               list:
                   title: "Lista de Noticias"
                   fields:
                     - id
                     - titulo
                     - publica
                     - portada
                     - { property: 'image', type: 'image', base_path: '/files/images' }
                     - { property: 'fecha', type: 'datetime'}
                     - tematica
                     - autor_noticia
                     - autor_foto_portada
                     - visitas
                     - comentarios
               form:
                  fields:
                      - titulo
                      - resumen
                      - cuerpo
                      - publica
                      - portada
                      - { property: 'imageFile', type: 'vich_image' }
                      - fecha
                      - tematica
                      - autor_noticia
                      - autor_foto_portada
           Comentarios:
               class: App\Entity\Comentarios
               form:
                  fields:
                      - nombre
                      - { property: 'email', type: 'email' }
                      - cuerpo_comen
                      - fecha
                      - publicado
                      - noticia_id
           RespuestaComentario:
               class: App\Entity\RespuestaComentario
               form:
                  fields:
                      - nombre
                      - { property: 'correo', type: 'email' }
                      - cuerpoComentario
                      - fecha
                      - publicado
                      - comentario
           CategoriasRecursosInformacion:
               class: App\Entity\CategoriasRecursosInformacion
               form:
                  fields:
                      - nombre
                      - descripcion
           RecursosInformacion:
               class: App\Entity\RecursosInformacion
               list:
                  fields:
                      - id
                      - { property: 'url', type: 'url' }
                      - { property: 'image', type: 'image', base_path: '/files/imagesRecursosinformacion' }
                      - nombre
                      - categoria
               form:
                  fields:
                      - { property: 'url', type: 'url' }
                      - { property: 'imageFile', type: 'vich_image' }
                      - nombre
                      - descripcion
                      - categoria

