#easy_admin:
#    entities:
#        # List the entity class name you want to manage
#        - App\Entity\Product
#        - App\Entity\Category
#        - App\Entity\User
easy_admin:
   site_name: 'CRAI <em style="font-size: 80%;">Administration.</em>'
   design:
           brand_color: '#1ABC9C'
           form_theme: 'vertical'
           menu:
               - label: 'Noticias'
                 children:
                   - { label: 'Noticias', icon: 'list', entity: 'Noticias' }
                   - { label: 'Comentarios', icon: 'list', entity: 'Comentarios' }
                   - { label: 'Respuestas a Comentarios', icon: 'list', entity: 'RespuestaComentario' }
               - label: 'Recursos'
                 children:
                   - { label: 'Categorias', icon: 'list', entity: 'CategoriasRecursosInformacion' }
                   - { label: 'Recursos de la Informacion', icon: 'list', entity: 'RecursosInformacion' }
               - label: 'Departamento'
                 children:
                   - { label: 'Departamentos', icon: 'list', entity: 'Departamentos' }
                   - { label: 'Salas', icon: 'list', entity: 'Salas' }
                   - { label: 'Usuarios', icon: 'list', entity: 'Usuarios' }
                   - { label: 'Grupos de Trabajo', icon: 'list', entity: 'GruposDeTrabajo' }
               - { label: '----------------------@@@@@@@@@@---------------------' }
               - { label: 'Documentos', icon: 'list', entity: 'Documentos' }
               - { label: 'Reservas de Salas', icon: 'list', entity: 'Quienreserva' }
               - { label: 'Contacto', icon: 'list', entity: 'Contacto' }
               - { label: 'Visita guiada', icon: 'list', entity: 'Vguiada' }
               - { label: '----------------------@@@@@@@@@@---------------------' }
               - { label: 'Plan de Resultados Individuales', icon: 'list', entity: 'PlanResultadosIndividuales' }
               - { label: 'Plan de Trabajo Mensual', icon: 'list', entity: 'PlanTrabajoMensual' }
   formats:
       date:     'd/m/Y'
       time:     'H:i'
       datetime: 'd/m/Y H:i:s'
   entities:
           PlanTrabajoMensual:
               class: App\Entity\PlanTrabajoMensual
               list:
                  title: "Planes de Trabajo Mensual(PTM)"
                  fields:
                      - id
                      - { property: 'file', type: 'file', base_path: '/files/documentosPTM/' }
                      - fecha
               form:
                  help: 'Los nombres de los ficheros no deben ser largos. Maximo 15 caracteres'
                  title: "Nuevo Plan de Resultados Mensual"
                  fields:
                      - { type: 'group', css_class: 'col-sm-4', label: 'Informacion' }
                      - { property: 'docFile',label: 'Documento', type: 'file' }
                      - descripcion
           PlanResultadosIndividuales:
               class: App\Entity\PlanResultadosIndividuales
               list:
                  title: "Planes de Resultados Individuales(PRI)"
                  fields:
                      - id
                      - { property: 'file', type: 'file', base_path: '/files/documentosPRI/' }
                      - trabajador
                      - fecha
               form:
                  title: "Nuevo Plan de Resultados Individuales"
                  fields:
                      - { type: 'group', css_class: 'col-sm-4', label: 'Informacion' }
                      - { property: 'docFile',label: 'Documento', type: 'file' }
                      - trabajador
                      - { type: 'group', css_class: 'col-sm-4', label: 'Comentario' }
                      - descripcion
           Vguiada:
               class: App\Entity\Vguiada
               form:
                  title: "Nueva Visita guiada"
                  fields:
                      - { type: 'group', css_class: 'col-sm-8', label: 'Informacion Personal', icon: 'user' }
                      - { property: 'nombre', label: 'Nombre', type: 'text' }
                      - { property: 'facultad', label: 'Facultad', type: 'text' }
                      - { property: 'correo', label: 'Correo', type: 'email' }
                      - { property: 'carrera', label: 'Carrera', type: 'text' }
                      - { type: 'group', label: 'Contenido', css_class: 'col-sm-4' }
                      - fecha
                      - cantidadestudiantes
           Contacto:
               class: App\Entity\Contacto
               form:
                  title: "Nuevo Contacto"
                  fields:
                      - { type: 'group', css_class: 'col-sm-8', label: 'Informacion Personal', icon: 'user' }
                      - { property: 'nombre', label: 'Nombre', type: 'text' }
                      - { property: 'pais', label: 'Pais', type: 'text' }
                      - { property: 'correo', label: 'Correo', type: 'email' }
                      - { property: 'trabajo', label: 'Pais', type: 'text' }
                      - { type: 'group', label: 'Contenido', css_class: 'col-sm-4' }
                      - contenido


           Quienreserva:
               class: App\Entity\Quienreserva
               list:
                  title: "Reservas de Salas"
                  fields:
                      - id
                      - nombre
                      - departamento
                      - publica
                      - correo
                      - horainicio
                      - horafin
                      - { property: 'cantidadparticipantes', label: 'Cantidad de Participantes' }
               form:
                  title: "Reservar Sala"
                  fields:
                      - { type: 'group', css_class: 'col-sm-8', label: 'Informacion Personal', icon: 'user' }
                      - { property: 'nombre', label: 'Nombre', type: 'text' }
                      - { property: 'departamento', label: 'Departamento', type: 'text' }
                      - sala
                      - Objetivo
                      - { type: 'group', label: 'Informacion de Contacto', icon: 'phone', css_class: 'col-sm-4' }
                      - { property: 'correo', label: 'Correo', type: 'email' }
                      - { property: 'horainicio', label: 'Fecha y Hora de Inicio', type: 'datetime' }
                      - { property: 'horafin', label: 'Fecha y Hora de Fin', type: 'datetime' }
                      - { property: 'cantidadparticipantes', label: 'Cantidad de Participantes' }
                      - { type: 'group', label: 'Administrador', icon: 'phone', css_class: 'col-sm-4' }
                      - publica
                      - quienautoriza
           Documentos:
               class: App\Entity\Documentos
               list:
                  fields:
                      - id
                      - nombre
                      - { property: 'file', type: 'file', base_path: '/files/documentoscrai/' }
               form:
                  fields:
                      - nombre
                      - { property: 'docFile',label: 'Documento', type: 'file' }
                      - descripcion
           GruposDeTrabajo:
               class: App\Entity\GruposDeTrabajo
               form:
                  fields:
                      - nombre
                      - descripcion
           Departamentos:
               class: App\Entity\Departamentos
               form:
                  fields:
                      - nombre
                      - descripcion
           Salas:
               class: App\Entity\Salas
           Usuarios:
               class: App\Entity\Usuarios
               list:
                   title: "Lista de Noticias"
                   fields:
                     - id
                     - { property: 'image', type: 'image', base_path: '/files/fotostrabajadores' }
                     - nombre
                     - correo
                     - EsDocente
                     - telefono
                     - cargo
                     - funcion
                     - departamento
                     - categoriadocente
                     - CategoriaCientifica
                     - grupodetrabajo


               form:
                  fields:
                      - { type: 'group', css_class: 'col-sm-4', label: 'Informacion Personal', icon: 'user' }
                      - DNI
                      - { property: 'nombre', label: 'Nombre', type: 'text' }
                      - { property: 'EstadoCivil', label: 'Estado Civil', type: 'text' }
                      - { property: 'nivelescolar', label: 'Nivel Escolar', type: 'text' }
                      - { property: 'fechanacimiento', label: 'Fecha de Nacimiento', type: 'date' }
                      - { property: 'imageFile', type: 'vich_image' }
                      - { type: 'group', label: 'Informacion de Contacto', icon: 'phone', css_class: 'col-sm-4' }
                      - { property: 'correo', label: 'Correo', type: 'email' }
                      - { property: 'telefono', label: 'Telefono fijo', type: 'text' }
                      - { property: 'numerocelular', label: 'Movil', type: 'text' }
                      - direccionparticular
                      - { type: 'group', label: 'Informacion Laboral y Profesional', icon: 'work', css_class: 'col-sm-4' }
                      - { property: 'cargo', label: 'Cargo', type: 'text' }
                      - { property: 'funcion', label: 'Funcion que realiza', type: 'text' }
                      - { property: 'categoriadocente', label: 'Categoria Docente', type: 'text' }
                      - { property: 'CategoriaCientifica', label: 'Categoria Cientifica', type: 'text' }
                      - departamento
                      - grupodetrabajo
                      - EsDocente


           Noticias:
               class: App\Entity\Noticias
               label: 'Noticias'
               list:
                   title: "Lista de Noticias"
                   fields:
                     - id
                     - titulo
                     - publica
                     - portada
                     - { property: 'image', type: 'image', base_path: '/files/images' }
                     - { property: 'fecha', type: 'datetime'}
                     - tematica
                     - autor_noticia
                     - autor_foto_portada
                     - visitas
                     - comentarios
               form:
                  fields:
                      - titulo
                      - resumen
                      - cuerpo
                      - publica
                      - portada
                      - { property: 'imageFile', type: 'vich_image' }
                      - fecha
                      - tematica
                      - autor_noticia
                      - autor_foto_portada
           Comentarios:
               class: App\Entity\Comentarios
               form:
                  fields:
                      - nombre
                      - { property: 'email', type: 'email' }
                      - cuerpo_comen
                      - fecha
                      - publicado
                      - noticia_id
           RespuestaComentario:
               class: App\Entity\RespuestaComentario
               form:
                  fields:
                      - nombre
                      - { property: 'correo', type: 'email' }
                      - cuerpoComentario
                      - fecha
                      - publicado
                      - comentario
           CategoriasRecursosInformacion:
               class: App\Entity\CategoriasRecursosInformacion
               form:
                  fields:
                      - nombre
                      - descripcion
           RecursosInformacion:
               class: App\Entity\RecursosInformacion
               list:
                  fields:
                      - id
                      - { property: 'url', type: 'url' }
                      - { property: 'image', type: 'image', base_path: '/files/imagesRecursosinformacion' }
                      - nombre
                      - categoria
               form:
                  fields:
                      - { property: 'url', type: 'url' }
                      - { property: 'imageFile', type: 'vich_image' }
                      - nombre
                      - descripcion
                      - categoria

