#easy_admin:
#    entities:
#        # List the entity class name you want to manage
#        - App\Entity\Product
#        - App\Entity\Category
#        - App\Entity\User
easy_admin:
   site_name: 'CRAI <em style="font-size: 80%;">Administration.</em>'
   design:
           brand_color: '#1ABC9C'
   formats:
       date:     'd/m/Y'
       time:     'H:i'
       datetime: 'd/m/Y H:i:s'
   entities:
           Noticias:
               class: App\Entity\Noticias
               label: 'Noticias'
               list:
                   title: "Lista de Noticias"
                   fields:
                     - id
                     - titulo
                     - resumen
                     - cuerpo
                     - publica
                     - portada
                     - { property: 'image', type: 'image', base_path: '/files/images' }
                     - { property: 'fecha', type: 'datetime'}
                     - tematica
                     - autor_noticia
                     - autor_foto_portada
                     - visitas
               form:
                  fields:
                      - titulo
                      - resumen
                      - { property: 'cuerpo', type: 'text' }
                      - publica
                      - portada
                      - { property: 'imageFile', type: 'vich_image' }
                      - fecha
                      - tematica
                      - autor_noticia
                      - autor_foto_portada
                      - visitas
           Comentarios:
               class: App\Entity\Comentarios
               form:
                  fields:
                      - nombre
                      - { property: 'email', type: 'email' }
                      - cuerpo_comen
                      - fecha
                      - publicado
                      - noticia_id

