sonata_admin:
    title: 'CRAI Administracion'
    dashboard:
        blocks:
            - position: left
              type: sonata.admin.block.admin_list
              settings:
                  groups: [CRAI, Bibliotecas, Otros]
            - position: right
              type: sonata.admin.block.admin_list
              settings:
                  groups: [Formacion,Investigaciones , Noticias, Recursos]
        groups:
            app.admin.group.Noticias:
                label: Noticias
                items: ~
                roles: [ ROLE_USER, ROLE_EDITOR ]
            app.admin.group.Investigaciones:
                label: Investigaciones
                items: ~
                roles: [ ROLE_ADMIN ]
            app.admin.group.Recursos:
                label: Recursos
                items: ~
                roles: [ ROLE_ADMIN ]
            app.admin.group.Bibliotecas:
                label: Bibliotecas
                items: ~
                roles: [ ROLE_ADMIN ]
            app.admin.group.Formacion:
                label: Formacion
                items: ~
                roles: [ ROLE_ADMIN ]
            app.admin.group.CRAI:
                label: CRAI
                items: ~
                roles: [ ROLE_ADMIN ]
            app.admin.group.otros:
                label: Otros
                items: ~
                roles: [ ROLE_ADMIN ]


sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
