# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'
framework:
    # ...
    templating:
        engines: ['twig', 'php']
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    admin.TematicaNoticia:
        class: App\Admin\TematicaNoticiaAdmin
        arguments: [~, App\Entity\TematicaNoticia, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Categorias Noticias }
        public: true
    admin.Comentarios:
        class: App\Admin\ComentariosAdmin
        arguments: [~, App\Entity\Comentarios, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Comentarios }
        public: true
    admin.Noticias:
        class: App\Admin\NoticiasAdmin
        arguments: [~, App\Entity\Noticias, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Noticias }
        public: true
    admin.RespuestaComentario:
        class: App\Admin\RespuestaComentarioAdmin
        arguments: [~, App\Entity\RespuestaComentario, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Respuesta a Comentarios }
        public: true